title: Hanisha Vemireddy
description: Data Scientist | Statistics | Machine Learning | Decision Science
baseurl: ""
url: "https://hanishavemireddy.github.io"

remote_theme: abhinavs/moonwalk

plugins:
  - jekyll-remote-theme

theme_config:
  show_navbar: true
  show_footer: false
  show_copyright: false